export const yearsData = [
    {
        year: "2023",
    },
    {
        year: "2022",
    },
    {
        year: "2021",
    },
    {
        year: "2020",
    },
    {
        year: "2019",
    },
    {
        year: "2018",
    },
    {
        year: "2017",
    },
    {
        year: "2016",
    },
    {
        year: "2015",
    },
    {
        year: "2014",
    },
    {
        year: "2013",
    },
    {
        year: "2012",
    },
    {
        year: "2011",
    },
    {
        year: "2010",
    },
    {
        year: "2009",
    },
    {
        year: "2008",
    },
    {
        year: "2007",
    },
    {
        year: "2006",
    },
    {
        year: "2005",
    },
    {
        year: "2004",
    },
    {
        year: "2003",
    },
    {
        year: "2002",
    },
    {
        year: "2001",
    },
    {
        year: "1996 - 2000",
    },
];
export const categoriesSlug = [
    "4Runner",
    "Allex",
    "Alphard",
    "Altezza",
    "Allion",
    "Aristo",
    "Aurion",
    "Auris",
    "Avalon",
    "Avanza",
    "Avensis",
    "Avensis Verso",
    "Aygo",
    "BA",
    "Bandeirante",
    "bB",
    "Belta",
    "Blade",
    "Blizzard",
    "Brevis",
    "C-HR",
    "Caldina",
    "Cami",
    "Camry",
    "Carina",
    "Carina E",
    "Carina ED",
    "Carina II",
    "Celica",
    "Century",
    "Chaser",
    "Coaster",
    "Corolla",
    "Corolla Axio",
    "Corolla Ceres",
    "Corolla Cross",
    "Corolla Fielder",
    "Corolla FX",
    "Corolla II",
    "Corolla Levin",
    "Corolla Rumion",
    "Corolla Runx",
    "Corolla Spacio",
    "Corolla Verso",
    "Corsa",
    "Cressida",
    "Cresta",
    "Crown",
    "Crown Majesta",
    "Curren",
    "Cynos",
    "D-4D 180 Clean",
    "Deliboy",
    "Duet",
    "Dyna",
    "Echo",
    "Esquire",
    "Estima",
    "Estima Emina",
    "Estima Lucida",
    "Etios",
    "FJ Cruiser",
    "Fortuner",
    "Funcargo",
    "Gaia",
    "Grand Hiace",
    "Granvia",
    "GT 86",
    "Harrier",
    "Harrier Hybrid",
    "Hiace",
    "Hiace Regius",
    "Highlander",
    "Hilux Pick Up",
    "Hilux Surf",
    "Innova",
    "Ipsum",
    "iQ",
    "Isis",
    "ist",
    "Izoa",
    "JPN TAXI",
    "Kluger V",
    "Land Cruiser",
    "Land Cruiser Prado",
    "Lite Ace",
    "Lite Ace Noah",
    "Lite Ace Truck",
    "Mark II",
    "Mark II Wagon Blit",
    "Mark II Wagon Qualis",
    "Mark X",
    "Mark X Zio",
    "Master Ace Surf",
    "Matrix",
    "Mega Cruiser",
    "Mirai",
    "MR-S",
    "MR2",
    "Nadia",
    "Noah",
    "Opa",
    "Origin",
    "Paseo",
    "Passo",
    "Passo Sette",
    "Picnic",
    "Pixis Epoch",
    "Pixis Joy",
    "Pixis Mega",
    "Pixis Space",
    "Pixis Truck",
    "Pixis Van",
    "Platz",
    "Porte",
    "Premio",
    "Previa",
    "Prius",
    "Prius a",
    "Prius C",
    "Prius PHV",
    "Prius v",
    "Probox",
    "Progres",
    "Pronard",
    "Publica",
    "Ractis",
    "Raize",
    "Raum",
    "RAV4",
    "Regius",
    "Regius Ace",
    "Roomy",
    "Rush",
    "Sai",
    "Scepter",
    "Sequoia",
    "Sera",
    "Sienna",
    "Sienta",
    "Soarer",
    "Solara",
    "Soluna",
    "Spade",
    "Sparky",
    "Sprinter",
    "Sprinter Carib",
    "Sprinter Marino",
    "Sprinter Trueno",
    "Starlet",
    "Succeed",
    "Supra",
    "Tacoma",
    "Tank",
    "Tercel",
    "Touring Hiace",
    "Town Ace",
    "Town Ace Noah",
    "Town Ace Truck",
    "ToyoAce",
    "Tundra",
    "Urban Cruiser",
    "Vanguard",
    "Vellfire",
    "Venza",
    "Verossa",
    "Verso",
    "Verso-s",
    "Vios",
    "Vista",
    "Vista Ardeo",
    "Vitz",
    "Voltz",
    "Voxy",
    "Wigo",
    "WiLL Cypha",
    "WiLL Vi",
    "WiLL VS",
    "Windom",
    "Wish",
    "Yaris",
];

export const categoriesData = [
    {
        name: 'Toyota',
        tags: [
            "4Runner",
            "Allex",
            "Alphard",
            "Altezza",
            "Allion",
            "Aristo",
            "Aurion",
            "Avalon",
            "Avanza",
            "Avensis",
            "Avensis Verso",
            "Aygo",
            "BA",
            "Bandeirante",
            "bB",
            "Belta",
            "Blade",
            "Blizzard",
            "Brevis",
            "C-HR",
            "Caldina",
            "Cami",
            "Camry",
            "Carina",
            "Carina E",
            "Carina ED",
            "Carina II",
            "Celica",
            "Century",
            "Chaser",
            "Coaster",
            "Corolla",
            "Corolla Axio",
            "Corolla Ceres",
            "Corolla Cross",
            "Corolla Fielder",
            "Corolla FX",
            "Corolla II",
            "Corolla Levin",
            "Corolla Rumion",
            "Corolla Runx",
            "Corolla Spacio",
            "Corolla Verso",
            "Corsa",
            "Cressida",
            "Cresta",
            "Crown",
            "Crown Majesta",
            "Curren",
            "Cynos",
            "D-4D 180 Clean",
            "Deliboy",
            "Duet",
            "Dyna",
            "Echo",
            "Esquire",
            "Estima",
            "Estima Emina",
            "Estima Lucida",
            "Etios",
            "FJ Cruiser",
            "Fortuner",
            "Funcargo",
            "Gaia",
            "Grand Hiace",
            "Granvia",
            "GT 86",
            "Harrier",
            "Harrier Hybrid",
            "Hiace",
            "Hiace Regius",
            "Highlander",
            "Hilux Pick Up",
            "Hilux Surf",
            "Innova",
            "Ipsum",
            "iQ",
            "Isis",
            "ist",
            "Izoa",
            "JPN TAXI",
            "Kluger V",
            "Land Cruiser",
            "Land Cruiser Prado",
            "Lite Ace",
            "Lite Ace Noah",
            "Lite Ace Truck",
            "Mark II",
            "Mark II Wagon Blit",
            "Mark II Wagon Qualis",
            "Mark X",
            "Mark X Zio",
            "Master Ace Surf",
            "Matrix",
            "Mega Cruiser",
            "Mirai",
            "MR-S",
            "MR2",
            "Nadia",
            "Noah",
            "Opa",
            "Origin",
            "Paseo",
            "Passo",
            "Passo Sette",
            "Picnic",
            "Pixis Epoch",
            "Pixis Joy",
            "Pixis Mega",
            "Pixis Space",
            "Pixis Truck",
            "Pixis Van",
            "Platz",
            "Porte",
            "Premio",
            "Previa",
            "Prius",
            "Prius a",
            "Prius C",
            "Prius PHV",
            "Prius v",
            "Probox",
            "Progres",
            "Pronard",
            "Publica",
            "Ractis",
            "Raize",
            "Raum",
            "RAV4",
            "Regius",
            "Regius Ace",
            "Roomy",
            "Rush",
            "Sai",
            "Scepter",
            "Sequoia",
            "Sera",
            "Sienna",
            "Sienta",
            "Soarer",
            "Solara",
            "Soluna",
            "Spade",
            "Sparky",
            "Sprinter",
            "Sprinter Carib",
            "Sprinter Marino",
            "Sprinter Trueno",
            "Starlet",
            "Succeed",
            "Supra",
            "Tacoma",
            "Tank",
            "Tercel",
            "Touring Hiace",
            "Town Ace",
            "Town Ace Noah",
            "Town Ace Truck",
            "ToyoAce",
            "Tundra",
            "Urban Cruiser",
            "Vanguard",
            "Vellfire",
            "Venza",
            "Verossa",
            "Verso",
            "Verso-s",
            "Vios",
            "Vista",
            "Vista Ardeo",
            "Vitz",
            "Voltz",
            "Voxy",
            "Wigo",
            "WiLL Cypha",
            "WiLL Vi",
            "WiLL VS",
            "Windom",
            "Wish",
        ],
    },
    {
        name: 'Lexus',
        tags: [
            'CT200h',
            'ES200', 'ES250', 'ES300', 'ES300h', 'ES330', 'ES350',
            'GS F', 'GS200t', 'GS250', 'GS300', 'GS300h', 'GS350', 'GS400', 'GS430', 'GS450h', 'GS460', 'GX460', 'GX470',
            'HS250h',
            'IS F', 'IS200', 'IS200d', 'IS200t', 'IS220d', 'IS250', 'IS250C', 'IS300', 'IS300h', 'IS350', 'IS350C',
            'LC500', 'LC500h', 'LFA', 'LM300h', 'LS350', 'LS400', 'LS430', 'LS460', 'LS460L', 'LS500', 'LS500h', 'LS600h', 'LS600hL', 'LX450', 'LX450d', 'LX470', 'LX570',
            'NX200', 'NX200t', 'NX250', 'NX300', 'NX300h', 'NX350h',
            'SC300', 'SC400', 'SC430',
            'UX200', 'UX250h'
        ],
    },
    {
        name: 'Mitsubishi',
        tags: [
            'Airtrek', 'Aspire',
            'Bravo',
            'Carisma', 'Challenger', 'Chariot', 'Chariot Grandis', 'Colt',
            'Debonair', 'Delica', 'Delica D:5', 'Diamante', 'Dignity', 'Dion',
            'Eclipse', 'eK Active', 'eK classy', 'eK Wagon', 'Emeraude', 'Eterna',
            'FTO',
            'Galant', 'Galant Fortis', 'Grandis', 'GTO',
            'i',
            'Jeep',
            'Lancer', 'Lancer Cedia', 'Lancer Evolution', 'Legnum', 'Libero',
            'Minica', 'Minica Toppo', 'Minicab', 'Mirage', 'Mirage Dingo',
            'Outlander',
            'Pajero', 'Pajero iO', 'Pajero Junior', 'Pajero Mini', 'Proudia',
            'RVR',
            'Sigma', 'Starion', 'Strada',
            'Toppo BJ', 'Toppo BJ Wide', 'Town Box', 'Town Box Wide', 'Triton'
        ],
    },
    {
        name: 'Honda',
        tags: [
            'Accord', 'Accord Inspire', 'Acty', 'Acty Truck', 'Acty Van', 'Airwave', 'Ascot', 'Ascot Innova', 'Avancier',
            'Ballade', 'Beat',
            'Capa', 'City', 'Civic', 'Civic Ferio', 'Civic Hybrid', 'Civic Shuttle', 'Concerto', 'CR-V', 'CR-X', 'CR-X del Sol', 'Crossroad',
            'Domani',
            'Edix', 'Element', 'Elysion',
            'Fit', 'Fit Aria', 'FR-V', 'Freed',
            'HR-V',
            'Insight', 'Inspire', 'Integra', 'Integra SJ',
            'Jazz',
            'Lagreat', 'Legend', 'Legend Coupe', 'Life', 'Life Dunk', 'Logo',
            'MDX', 'Mobilio', 'Mobilio Spike', 'MR-V',
            'NSX',
            'Odyssey', 'Orthia',
            'Partner', 'Pilot', 'Prelude',
            'Quintet',
            'Rafaga',
            'S-MX', 'S2000', 'Saber', 'Shuttle', 'Stepwgn', 'Stream',
            "That's", 'Today', 'Torneo',
            'Vamos', 'Vamos Hobio', 'Vigor',
            'Z', 'Zest'

        ],
    },
    {
        name: 'Mazda',
        tags: [
            '121', '323', '323F', '626', '929',
            'Atenza', 'Atenza Sport', 'Autozam AZ-1', 'Autozam AZ-3', 'Autozam Carol', 'Autozam Clef', 'Autozam Revue', 'Autozam Scrum', 'Axela', 'AZ-Offroad', 'AZ-Wagon',
            'Biante', 'Bongo', 'Bongo Brawny', 'Bongo Friendee', 'BT-50',
            'Capella', 'Carol', 'Cronos', 'CX-3', 'CX-5', 'CX-7', 'CX-9',
            'Demio',
            'Efini MS-8', 'Eunos 100', 'Eunos 300', 'Eunos 500', 'Eunos 800', 'Eunos Cargo', 'Eunos Cosmo', 'Eunos Presso',
            'Familia',
            'Lantis', 'Laputa', 'Luce',
            'Mazda2', 'Mazda3', 'Mazda5', 'Mazda6', 'Mazda6 MPS', 'Millenia', 'MPV', 'MX-3', 'MX-5', 'MX-6',
            'Persona', 'Premacy', 'Proceed', 'Proceed Levante',
            'Revue', 'Roadster', 'RX-7', 'RX-8',
            'Savanna RX-7', 'Scrum', 'Sentia', 'Spiano',
            'Titan', 'Tribute',
            'Verisa',
            'Xedos 6', 'Xedos 9'

        ],
    },
    {
        name: 'Nissan',
        tags: [
            '100NX', '180SX', '200SX', '240SX', '300ZX', '350Z', '370Z',
            'AD', 'Almera', 'Altima', 'Armada', 'Atlas', 'Auster', 'Avenir',
            'Bassara', 'BE-1', 'Bluebird', 'Bluebird Sylphy',
            'Cabstar', 'Caravan', 'Cedric', 'Cefiro', 'Cima', 'Civilian', 'Clipper', 'Crew', 'Cube', 'Cube Cubic',
            'Datsun', 'Dualis',
            'e-NV200', 'Elgrand', 'Exa', 'Expert',
            'Fairlady Z', 'Figaro', 'Frontier', 'Fuga',
            'Gloria', 'GT-R',
            'Homy', 'Hypermini',
            'Juke',
            'Kicks', 'King Cab', 'Kix',
            'Lafesta', 'Langley', 'Largo', 'Latio', 'Laurel', 'Leaf', 'Leopard', 'Liberty', 'Lucino',
            'March', 'March Box', 'Maxima', 'Micra', 'Micra C+C', 'Mistral', 'Moco', 'Murano',
            'Navara', 'Note', 'NP300', 'NV200',
            'Otti',
            'Pao', 'Pathfinder', 'Patrol', 'Pino', 'Pixo', 'Prairie', 'Prairie Joy', 'Presage', 'Presea', 'President', 'Primera', 'Primera Camino', 'Pulsar',
            'Qashqai', 'Qashqai+2', 'Quest',
            'R nessa', 'Rasheen', 'Rogue',
            'S-Cargo', 'Safari', 'Sentra', 'Serena', 'Silvia', 'Skyline', 'Skyline GT-R', 'Stagea', 'Stanza', 'Sunny', 'Sunny California', 'Sunny RZ-1', 'Sylphy',
            'Teana', 'Terrano', 'Terrano II', 'Terrano Regulus', 'Tiida', 'Tiida Latio', 'Tino', 'Titan',
            'Urvan',
            'Vanette', 'Vanette Serena', 'Vanette Truck', 'Versa', 'Volkswagen Santana',
            'Wingroad',
            'X-Trail', 'Xterra'

        ],
    },
    {
        name: 'Infiniti',
        tags: [
            'EX35', 'EX37',
            'FX35', 'FX37', 'FX45', 'FX50',
            'G20', 'G25', 'G35', 'G37',
            'I30', 'I35',
            'J30',
            'M25', 'M35', 'M35 Hybrid', 'M37', 'M45', 'M56',
            'Q30', 'Q40', 'Q45', 'Q50', 'Q60', 'Q70', 'QX30', 'QX4', 'QX50', 'QX56', 'QX60', 'QX70', 'QX80'

        ],
    },
    {
        name: 'Subaru',
        tags: [
            'Alcyone',
            'BRZ',
            'Domingo',
            'Exiga', 'Exiga Crossover 7',
            'Forester',
            'Impreza', 'Impreza WRX', 'Impreza WRX STI', 'Impreza XV',
            'Justy',
            'Legacy', 'Legacy B4', 'Legacy Lancaster', 'Leone',
            'Outback',
            'Pleo',
            'R1', 'R2', 'Rex',
            'Sambar', 'Stella',
            'Traviq',
            'Vivio',
            'XV'

        ],
    },
    {
        name: 'Suzuki',
        tags: [
            'Aerio', 'Alto', 'Alto Lapin',
            'Cappuccino', 'Carry Truck', 'Cervo', 'Cultus', 'Cultus Crescent',
            'Escudo', 'Esteem', 'Every',
            'Fronte',
            'Grand Escudo',
            'Jimny', 'Jimny Sierra', 'Jimny Wide',
            'Kei',
            'Landy',
            'MR Wagon',
            'Swift', 'SX4',
            'Twin',
            'Wagon R', 'Wagon R Plus', 'Wagon R Solio', 'Wagon R Wide',
            'X-90'

        ],
    },

]


